// <auto-generated />
using System;
using FinanzasMiHogar.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinanzasMiHogar.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("FinanzasMiHogar.App.Dominio.Gastos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("TipoGasto")
                        .HasColumnType("int");

                    b.Property<string>("fechaPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("montoDinero")
                        .HasColumnType("int");

                    b.Property<string>("nombreGastos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("periodoGastos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("gasto");
                });

            modelBuilder.Entity("FinanzasMiHogar.App.Dominio.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("gastoId")
                        .HasColumnType("int");

                    b.Property<string>("nombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("topeGastos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("gastoId");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("FinanzasMiHogar.App.Dominio.Usuarios", b =>
                {
                    b.HasOne("FinanzasMiHogar.App.Dominio.Gastos", "gasto")
                        .WithMany()
                        .HasForeignKey("gastoId");

                    b.Navigation("gasto");
                });
#pragma warning restore 612, 618
        }
    }
}
